# SPDX-License-Identifier:      GPL-2.0+
#
# Copyright 2014 Freescale Semiconductor, Inc.
#
# Copyright 2017-2019 NXP
#
#

obj-y += ls1021atsn.o
obj-$(CONFIG_FSL_DCU_FB) += dcu.o
obj-$(CONFIG_ARMV7_PSCI) += psci.o
