#
# Copyright 2018-2021 NXP
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += app.o
obj-$(CONFIG_GPIO_COREID_SET)	+= test_gpio.o
obj-$(CONFIG_I2C_COREID_SET)	+= test_i2c.o
obj-$(CONFIG_IRQ_COREID_SET)	+= test_irq_init.o
obj-$(CONFIG_ICC_COREID_SET)	+= test_icc.o
